### ISSUE TITLE
Navigation links should not be buttons

### ISSUE THREAD

**Issue by CKH4** [opacity/webinterface#111]
They should use be using the `Link` element from `react-router-dom` which wraps an anchor tag with browser history navigation

**Comment by funkydrummer** [comment]
@CKH4 is this still active and being worked?

**Comment by CKH4** [comment]
I was never working on it outside of seeing if it was a quick fix. That'd be something for Edmund or Ladislav to handle. I think it is tied to the dependency issues we are having

**Comment by funkydrummer** [comment]
@EdmundMai let me know if you think this is an active issue or I should move to backlog.
