### ISSUE TITLE
Update links in Privacy Policy and Terms&Cond

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#123]
Opacity Website
Opacity Storage Portal
Opacity Blog
Opacity Twitter Page
Opacity Reddit
Opacity Telegram Channel
Opacity Trading Telegram Channel

**Comment by funkydrummer** [comment]
These still need to be updated, @tenisakb 

Term of Service: https://www.opacity.io/terms-of-service
Opacity Website
Opacity Storage Portal
Opacity Reddit

Privacy Policy: https://www.opacity.io/privacy-policy
Opacity Reddit

**Comment by tenisakb** [comment]
Its changed in https://github.com/opacity/webinterface/pull/127
