### ISSUE TITLE
Add LinkedIn and bios on team page

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#124]

**Comment by MrRedPandabear** [comment]
@funkydrummer Look who's silently watching

**Comment by tenisakb** [comment]
@funkydrummer can you describe me how it should looks like? I dont see design in zeplin - its not necessary but I wanna be sure.

![teampage](https://user-images.githubusercontent.com/7314503/55071599-5519b300-5089-11e9-81be-088cd50fabe6.png)

**Comment by funkydrummer** [comment]
For now, just add the LinkedIn icon in the bottom left corner with the person's link. We can add bios later from each person.

**Comment by funkydrummer** [comment]
Also add github icon/link next to LinkedIn, bottom left corner.
