### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#157]
https://docs.google.com/document/d/1UqswsiaaRL4oxe11HUPJ04Jg4hroCiRh6xYybk8vbbo/edit?usp=sharing

**Comment by funkydrummer** [comment]
@tenisakb updated doc with more items.

**Comment by funkydrummer** [comment]
cool new features

**Comment by MutsiMutsi** [comment]
@funkydrummer WAT IS DIS
