### ISSUE TITLE
Add captcha to Sign up

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#208]

**Comment by tenisakb** [comment]
@funkydrummer @EdmundMai I think a good choice can be https://developers.google.com/recaptcha/docs/versions reCAPTCHA v2 (Invisible reCAPTCHA badge).. do you agree?

**Comment by funkydrummer** [comment]
Yes

**Comment by EdmundMai** [comment]
@tenisakb use this: https://github.com/appleboy/react-recaptcha
