### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#211]
I will add more detail...

**Comment by funkydrummer** [comment]
Add waiting indicator like a moving bar on the payments page.

**Comment by funkydrummer** [comment]
![text spacing.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/56549570-e545-4ba6-b474-3b7af63925ec)

**Comment by funkydrummer** [comment]
![Capitals.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/2cf2c186-e11e-485b-b005-b8c90f47b7f8)

**Comment by funkydrummer** [comment]
![pin2.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/31802593-54c9-40ec-b837-0b9b3c6d8657)![Pin.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/a9c815e8-b5bb-4380-a508-2a6669522997)

**Comment by funkydrummer** [comment]
![login signup.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/080f4b5a-e855-4596-9aa1-59ea71735ae9)

Make buttons same order: Login left, Signup right

**Comment by funkydrummer** [comment]
![Title.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/72b80bd3-9946-49e8-ac78-70716d9f58cf)

Change page title to 'Opacity - Handle Your Privacy'

**Comment by funkydrummer** [comment]
![team.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/b1e51c1e-4074-4ae8-adb3-a2a5094d6f75)

**Comment by funkydrummer** [comment]
![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/9a17b02f-3fc5-46c2-9188-cdc9db823e15)

**Comment by MrRedPandabear** [comment]
@funkydrummer Reminder: FIRST NAME + LAST NAME. And add text to each member, if everyone got some free time at some point to write a short about text about themselves.

**Comment by funkydrummer** [comment]
![save handle.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/05114964-c2b1-4663-8393-3b3f7fad64a1)

**Comment by funkydrummer** [comment]
![payment.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/279aa681-37de-45b8-afb8-af73e08ba0eb)

**Comment by funkydrummer** [comment]
![file manager view.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/0ba46677-6a0a-49a3-9f76-dc980f803004)

**Comment by funkydrummer** [comment]
Add Delete Confirmation to user when delete a file

**Comment by funkydrummer** [comment]
![empty files.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/75978581-c4e4-4a3b-8e32-f304eace0451)

**Comment by funkydrummer** [comment]
![share box.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/da1bfae2-b640-44cb-9b55-80202bb53cb8)

**Comment by funkydrummer** [comment]
![missing file.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/ff33f217-561e-473b-9aa8-bc74c3859855)

**Comment by funkydrummer** [comment]
![plans.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/9a6e6c9d-ea60-4a65-87d5-1f6cde42fd7b)

**Comment by funkydrummer** [comment]
![plan type.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/38fc12fa-262b-4a0f-adb3-86490d8f21c7)

For all Register screens

**Comment by funkydrummer** [comment]
Check headers for SEO.

**Comment by tenisakb** [comment]
On mobile the upload function is stucked at the same place. If I scroll down, it "disappears".
![photo_2019-05-27_13-02-09](https://user-images.githubusercontent.com/7314503/58415748-bd801300-807f-11e9-909f-21de70a9ea5c.jpg)

**Comment by funkydrummer** [comment]
![login signup buttons.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/b67e2526-7157-4000-985c-f5cdeae63cb8)

**Comment by funkydrummer** [comment]
Not all ui updates in place, but I'll wait for conflict resolved for other PRs.
