### ISSUE TITLE
rewrite sorting

### ISSUE THREAD

**Issue by tenisakb** [opacity/webinterface#215]

**Comment by funkydrummer** [comment]
![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/f3c69d56-62f6-451f-986c-d4b83a8aa4b5)

The sorting icon needs to switch to sorted column.
@tenisakb

**Comment by MrRedPandabaer** [comment]
@funkydrummer Maybe file type too (icon left)?
