### ISSUE TITLE
Preview files

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#220]

**Comment by funkydrummer** [comment]
Preview file on handle shared page

![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/b1d2e292-db0d-4bf0-a4f4-3b87942b7ce0)

**Comment by funkydrummer** [comment]
Preview file on file manager page

![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/8f427639-492e-498f-b45c-2bfce9b0fef3)

**Comment by funkydrummer** [comment]
Generate and store encrypted scaled version of file on upload to store for use.

**Comment by tenisakb** [comment]
@funkydrummer so in this issue I will implement only preview of files, it will be only on shared page? How can I get "preview version" of file? Maybe @EdmundMai can tell me something about it?

**Comment by funkydrummer** [comment]
https://files.slack.com/files-pri/T6Y63TG5Q-FMH0AGGRL/2019-08-16_0706.png
