### ISSUE TITLE
Page load speed improvements

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#229]
https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=desktop&url=http%3A%2F%2Fwww.opacity.io%2F

**Comment by tenisakb** [comment]
https://github.com/opacity/webinterface/pull/235

**Comment by funkydrummer** [comment]
![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/41a8e2aa-1af3-4fe5-9087-5c11bf0f7b8e)

**Comment by funkydrummer** [comment]
Enable gzip compression	
F (0)
 	SERVER	HIGH
What's this mean?
Enable compression for the following resources to reduce their transfer size by 1.9MiB (72% reduction).

Compressing https://beta.opacity.io/static/js/opacity-webinterface-0.0.1.min.js could save 1.7MiB (71% reduction).
Compressing https://beta.opacity.io/main.f7fe8ea438c1ebcad654.css could save 63.2KiB (78% reduction).
Compressing https://beta.opacity.io/static/media/info_personal.4506b34ce154313187d744984c75ed8f.svg could save 50.2KiB (80% reduction).
Compressing https://beta.opacity.io/static/media/info_cryptocurrency.c0bc07a0e9b1fb0f6edf62b6858cfdd1.svg could save 22.4KiB (75% reduction).
Compressing https://beta.opacity.io/static/media/benefit_files.1decc176bc41d388d545fa5d338147c9.svg could save 12.8KiB (70% reduction).
Compressing https://beta.opacity.io/static/media/info_opacity.73208be0101c3c7516eabd38e90eb3f5.svg could save 11.8KiB (75% reduction).
Compressing https://beta.opacity.io/static/media/benefit_handle.b32388dfdd27fa7f77f3ad7ec483faa9.svg could save 5.1KiB (73% reduction).
Compressing https://beta.opacity.io/static/media/credit.3d81bce56a7068cd4e3b4ef488afa529.svg could save 3.8KiB (71% reduction).
Compressing https://beta.opacity.io/static/media/pay_currency.eb27e6dd0c4049a93ea1231373c713ac.svg could save 3.2KiB (72% reduction).
Compressing https://beta.opacity.io/static/media/logo-login.feaf9900510d7de483419ecaf02d9681.svg could save 2.9KiB (58% reduction).
Compressing https://beta.opacity.io/static/media/info_benefit.0d6e176b4ac95575bf51462c22dd04cd.svg could save 2.2KiB (62% reduction).
Compressing https://beta.opacity.io/static/media/logo.345da994bab620c05eb8db8b42358fff.svg could save 1.8KiB (49% reduction).
Compressing https://beta.opacity.io/static/media/share_file.bcca8477ab4f39ad692742869ea73fbd.svg could save 1.6KiB (69% reduction).
Compressing https://beta.opacity.io/static/media/features.2962de431de75c578915089ff3105cd2.svg could save 1.2KiB (61% reduction).
Compressing https://beta.opacity.io/static/media/bubbles.c10a8830a98abd293e6951b0786119eb.svg could save 1018B (64% reduction).
Compressing https://beta.opacity.io/static/media/youtube.725a5914803f5b1054340090a9646882.svg could save 959B (57% reduction).
Compressing https://beta.opacity.io/static/media/twitter.f57517d02afbd7a9e344e8d10fa0c230.svg could save 942B (48% reduction).
Compressing https://beta.opacity.io/static/media/github.baeb4570394a1282181f8df065125f60.svg could save 767B (49% reduction).
Compressing https://beta.opacity.io/static/media/reddit.c39f26c155bf67686e5d6931dc2ef3a1.svg could save 571B (49% reduction).
Compressing https://opacity.io/widget.php could save 458B (57% reduction).
Compressing https://beta.opacity.io/static/media/telegram.d097f6e2f49c3e8aec2d67c6c36cea95.svg could save 185B (33% reduction).
Compressing https://beta.opacity.io/static/media/hamburger.1ac189748f70e962cf25333bd72b14ad.svg could save 163B (31% reduction).
Compressing https://beta.opacity.io/static/media/arrow_right.59534548d69ad24ba966afcc27f3b5fa.svg could save 124B (27% reduction).
Leverage browser caching	
F (0)
 	SERVER	HIGH
What's this mean?
Leverage browser caching for the following cacheable resources:

https://a.ad.gt/api/v1/u/matches/48 (expiration not specified)
https://beta.opacity.io/favicon.ico (expiration not specified)
https://beta.opacity.io/main.f7fe8ea438c1ebcad654.css (expiration not specified)
https://beta.opacity.io/static/js/opacity-webinterface-0.0.1.min.js (expiration not specified)
https://beta.opacity.io/static/media/arrow_right.59534548d69ad24ba966afcc27f3b5fa.svg (expiration not specified)
https://beta.opacity.io/static/media/benefit_files.1decc176bc41d388d545fa5d338147c9.svg (expiration not specified)
https://beta.opacity.io/static/media/benefit_handle.b32388dfdd27fa7f77f3ad7ec483faa9.svg (expiration not specified)
https://beta.opacity.io/static/media/bubbles.c10a8830a98abd293e6951b0786119eb.svg (expiration not specified)
https://beta.opacity.io/static/media/cossio.77887ec04a5eec170b747496e8ad8883.webp (expiration not specified)
https://beta.opacity.io/static/media/credit.3d81bce56a7068cd4e3b4ef488afa529.svg (expiration not specified)
https://beta.opacity.io/static/media/features.2962de431de75c578915089ff3105cd2.svg (expiration not specified)
https://beta.opacity.io/static/media/github.baeb4570394a1282181f8df065125f60.svg (expiration not specified)
https://beta.opacity.io/static/media/hamburger.1ac189748f70e962cf25333bd72b14ad.svg (expiration not specified)
https://beta.opacity.io/static/media/info_benefit.0d6e176b4ac95575bf51462c22dd04cd.svg (expiration not specified)
https://beta.opacity.io/static/media/info_cryptocurrency.c0bc07a0e9b1fb0f6edf62b6858cfdd1.svg (expiration not specified)
https://beta.opacity.io/static/media/info_opacity.73208be0101c3c7516eabd38e90eb3f5.svg (expiration not specified)
https://beta.opacity.io/static/media/info_personal.4506b34ce154313187d744984c75ed8f.svg (expiration not specified)
https://beta.opacity.io/static/media/kucoin.b04b7ec4505e7506bf7615d7c2fcbfee.webp (expiration not specified)
https://beta.opacity.io/static/media/logo-login.feaf9900510d7de483419ecaf02d9681.svg (expiration not specified)
https://beta.opacity.io/static/media/logo.345da994bab620c05eb8db8b42358fff.svg (expiration not specified)
https://beta.opacity.io/static/media/pay_currency.eb27e6dd0c4049a93ea1231373c713ac.svg (expiration not specified)
https://beta.opacity.io/static/media/reddit.c39f26c155bf67686e5d6931dc2ef3a1.svg (expiration not specified)
https://beta.opacity.io/static/media/share_file.bcca8477ab4f39ad692742869ea73fbd.svg (expiration not specified)
https://beta.opacity.io/static/media/telegram.d097f6e2f49c3e8aec2d67c6c36cea95.svg (expiration not specified)
https://beta.opacity.io/static/media/twitter.f57517d02afbd7a9e344e8d10fa0c230.svg (expiration not specified)
https://beta.opacity.io/static/media/youtube.725a5914803f5b1054340090a9646882.svg (expiration not specified)
https://opacity.io/widget.php (expiration not specified)
https://p.ad.gt/api/v1/p/passive/357a6a284a27299fa2b62aec583cf0bc/7a0eb41e-7457-451b-8e33-7fccbd011e90/48 (expiration not specified)
https://s3.us-east-2.amazonaws.com/opacity-public/whatIsOpacity.mov (expiration not specified)
https://use.typekit.net/xyb4auz.css (10 minutes)
https://www.googletagmanager.com/gtm.js?id=GTM-WBG5C67 (15 minutes)
https://www.google-analytics.com/plugins/ua/ec.js (1 hour)
https://www.google-analytics.com/plugins/ua/ecommerce.js (1 hour)
https://www.google-analytics.com/analytics.js (2 hours)

**Comment by funkydrummer** [comment]
[Uploading... image.png ]

**Comment by funkydrummer** [comment]
not seeing improvement

**Comment by tenisakb** [comment]
You are checking opacity.io, there is still old version.. you cant check beta.opacity.io - there is needy password. I checked on my private server, its a bit better but we still need more improvements

**Comment by funkydrummer** [comment]
- I also checked beta, removed the auth to test

**Comment by funkydrummer** [comment]
@rfornea 
https://developers.google.com/web/tools/lighthouse/audits/text-compression

https://computingforgeeks.com/how-to-enable-gzip-brotli-compression-for-nginx-on-linux/

Text compression on the server should get us a significant performance improvement, please set it up when you can.

**Comment by funkydrummer** [comment]
![image.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/77a0dd22-c1cd-45e1-b9c5-8ee466f56db7)

Much better performance now, closing.
