### ISSUE TITLE
Update the "Important" statement on payment screen.  

### ISSUE THREAD

**Issue by rfornea** [opacity/webinterface#236]
[This backend issue](https://github.com/opacity/storage-node/issues/194) will take some time to investigate and resolve, so in the meantime, update the "Important" statement on the payment screen to instruct the user not to send more or less than 2.0 OPQ or they may lose their funds.

**Comment by funkydrummer** [comment]
![2019-06-03_1453.png](https://images.zenhubusercontent.com/5c080096035895308911c7f6/de370276-0ddb-4f11-91f1-ea0d52a9c453)

**Comment by MrRedPandabear** [comment]
@funkydrummer It's not much effort to create the graphic. Ladislav and Edmund are working through the noted necessary changes.
