### ISSUE TITLE
Remove old logo

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#290]
Jet, [18.06.19 06:49]
[Forwarded from P.G.T. Beauregard]
Completely off topic but I also just realized if you share the download link from the opacity bot the old logo pops up in TG to

Jet, [18.06.19 06:50]
I tried the webpage bot, which didn't work.

Turns out the old logo is still linked in the head:
<meta property="og:image" content="/logo.png">

Jet, [18.06.19 06:50]
https://opacity.io/logo.png

**Comment by tenisakb** [comment]
https://github.com/opacity/webinterface/pull/291
