### ISSUE TITLE
Add link for new desktop app to website

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#378]
https://github.com/Mavahu/opacity-electron/releases/tag/v1.2.0

**Comment by Mavahu** [comment]
Please link to the general releases, so you don't need to update the link on every release.
e.g. https://github.com/Mavahu/opacity-electron/releases

**Comment by funkydrummer** [comment]
https://github.com/Mavahu/opacity-electron
https://github.com/act-opacity/ocelot

**Comment by funkydrummer** [comment]
Closing as duplicate to another open issue.
