### ISSUE TITLE
Outdated/deprecated/missing/incorrect/extra dependencies

### ISSUE THREAD

**Issue by CKH4** [opacity/webinterface#76]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Vulnerabilities:

- [ ] `handlebars` (dependency of `jest`)
- [ ] ... 28 others

Deprecated/outdated:

- [ ] `redux@^3.7.2` must be `4`
- [ ] `react-redux@^5.1.1` must be `6`
- [ ] `react-router-redux`

Missing:

- [ ] `eslint-config-react-app@2.1.0` requires a peer of `eslint@^4.1.1`
- [ ] `eslint-config-standard@12.0.0` requires a peer of `eslint-plugin-import@>=2.13.0`
- [ ] `eslint-plugin-import@2.8.0` requires a peer of `eslint@2.x - 4.x`
- [ ] `eslint-plugin-jsx-a11y@5.1.1` requires a peer of `eslint@^2.10.2 || ^3 || ^4`
- [ ] `eslint-plugin-react@7.4.0` requires a peer of `eslint@^3.0.0 || ^4.0.0`
- [ ] `extract-text-webpack-plugin@3.0.2` requires a peer of `webpack@^3.1.0`
- [ ] `sw-precache-webpack-plugin@0.11.4` requires a peer of `webpack@^1 || ^2 || ^2.1.0-beta || ^2.2.0-beta || ^3`
- [ ] `ts-jest@23.10.5` requires a peer of `jest@>=22 <24`
- [ ] `@types/react-router`
- [ ] `@types/react-router-dom`

Incorrect:

- [ ] `babel-jest` (set as both dev and regular dependency)

Extra:

- [ ] `preact`
- [ ] `lodash` (?)
- [ ] `postcss` (?)
- [ ] `react-showdown`
- [ ] ... review others in case there are more

**Comment by funkydrummer** [comment]
@EdmundMai still in progress or done?
